name: .NET Build
# Testing versioning

on:
  push:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Bump versions
        uses: SiqiLu/dotnet-bump-version@master
        with:
          version_files: "src/**/*.csproj"
          github_token: ${{ secrets.GITHUB_TOKEN }}