name: "Deploy NuGet Package"
on:
  push:
    tags:
      - 'v*'
env:
  CORE_PROJECT_PATH: 'src/IISLogManager.Core/IISLogManager.Core.csproj'
  CLI_PROJECT_PATH: 'src/IISLogManager.CLI/IISLogManager.CLI.csproj'
  PACKAGE_OUTPUT_DIR: ${{ github.workspace }}\output
  NUGET_SOURCE_URL: 'https://api.nuget.org/v3/index.json'

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: Restore packages
        run: dotnet restore ${{ env.CORE_PROJECT_PATH }}

      - name: Get Version
        id: version
        uses: batilla7/get-version-action@v2

      - name: Build packages
        run: dotnet build ${{ env.CORE_PROJECT_PATH }} --no-restore --configuration Release -p:Version=${{ steps.version.outputs.version-without-v }}


      - name: Pack packages
        run: dotnet pack ${{ env.CORE_PROJECT_PATH }} --no-restore --no-build --configuration Release --include-symbols -p:PackageVersion=${{ steps.version.outputs.version-without-v }} --output ${{ env.PACKAGE_OUTPUT_DIR }}
      
      -name: Push Package
        run: dotnet nuget push ${{ env.PACKAGE_OUTPUT_DIR }}\*.nupkg -k ${{ secrets.NUGET_AUTH_TOKEN }} -s ${{ env.NUGET_SOURCE_URL }}
        
      